apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    app: api
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 30%
      maxUnavailable: 20%
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: santiagopereyramarchetti/kubernetes-api:1.0
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "200m"
              memory: "64Mi"
          livenessProbe:
            tcpSocket:
              port: 9000
            initialDelaySeconds: 20
            periodSeconds: 30
            failureThreshold: 2
          readinessProbe:
            tcpSocket:
              port: 9000
            initialDelaySeconds: 10
            periodSeconds: 30
            failureThreshold: 1
          ports:
            - containerPort: 9000
          envFrom:
            - configMapRef:
                name: api
            # - secretRef:
            #     name: posts